
spring:
  profiles:
    active: dev
  application:
    name: 'flutter-service-demo'
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.18:3306/test?charaterEncoding=utf-8&useSSL=true
    username: admin
    password: 123456
  security:
    user:
      name: user
      password: 123456
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB

server:
  port: 9000
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  file:
    name: /Desktop/logs/flutter-demo.log
  logback:


fdfs:
  so-timeout: 1501
  connect-timeout: 601
  thumb-image:             #缩略图生成参数
    width: 150
    height: 150
  tracker-list:            #TrackerList参数,支持多个
    - 192.168.1.18:22122

flutter:
  jwt:
    secret: abc123456
    expire: 5
    cache-expire: 10