spring:
  application:
    name: 'flutter-service-demo'
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.18:3306/test?charaterEncoding=utf-8&useSSL=true*serverTimezone=Asia/Shanghai&useSSL=false
    username: admin
    password: 123456
  security:
    user:
      name: user
      password: 123456
  redis:
    database: 0
    host: 192.168.1.18
    port: 6379
  rabbitmq:
    host: 192.168.1.18
    port: 5672
    virtual-host: /
    username: test
    password: test

server:
  port: 9000

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  file:
    name: /Desktop/logs/flutter-demo.log
  logback:



flutter:
  jwt:
    secret: abc123456
    expire: 5
    cache-expire: 10