spring:
  application:
    name: 'flutter-service-demo'
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/user?charaterEncoding=utf-8&useSSL=true
    username: root
    password: 123456
server:
  port: 9000